# -*- coding: utf-8 -*-
"""KMeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JE0-O1MnNYqitv47qqlrxQEbKmvEXZSM
"""

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('Mall_Customers.csv')
data.head()

data = data.drop('CustomerID', axis=1)
data

data['Gender'] = data['Gender'].map({'Male':0, 'Female':1})
data

x = data.iloc[:,[2,3]].values
x

l = []
for i in range(1,11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 0)
    kmeans.fit(x)
    l.append(kmeans.inertia_)

plt.plot(range(1,11), l)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('l')
plt.show

KM = KMeans(n_clusters = 5, init = 'k-means++', random_state = 0)
y_means = KM.fit_predict(x)
y_means

plt.scatter(x[y_means == 0, 0], x[y_means == 0, 1], s = 100, c = 'red', label = 'Cluster 1')
plt.scatter(x[y_means == 1, 0], x[y_means == 1, 1], s = 100, c = 'blue', label = 'Cluster 2')
plt.scatter(x[y_means == 2, 0], x[y_means == 2, 1], s = 100, c = 'green', label = 'Cluster 3')
plt.scatter(x[y_means == 3, 0], x[y_means == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4')
plt.scatter(x[y_means == 4, 0], x[y_means == 4, 1], s = 100, c = 'magenta', label = 'Cluster 5')
plt.scatter(KM.cluster_centers_[:, 0], KM.cluster_centers_[:, 1], s = 300, c = 'black', label = 'Centroids')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix

sc = accuracy_score(y_means, y_means)
sc

cr = classification_report(y_means, y_means)
cr

sc = confusion_matrix(y_means, y_means)
sc